plugins {
    id "com.android.application"
}

android {
    namespace "com.ryza.chat"
    compileSdk 34

    defaultConfig {
        applicationId "com.ryza.chat.fish"
        minSdk 24
        targetSdk 34
        versionCode 18
        versionName "1.2.15"
    }

    buildTypes {
        release {
            minifyEnabled false
        }

        debug {
            debuggable true
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ["src/main/assets"]
        }
    }

    packaging {
        resources.excludes += "**/*.md"
    }
}
